---
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: demo-app:/Service:default/nginxservice
  name: nginxservice
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: nginxdeployment
  type: LoadBalancer
